//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalixtaSoapWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.calixtaondemand.com", ConfigurationName="CalixtaSoapWebService.GatewayPortType")]
    public interface GatewayPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajesAsync(CalixtaSoapWebService.Transaccion mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoEnvioEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EstadoEnvioEmailAsync(int cte, string email, string password, int id);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EventosEnvioEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        System.Threading.Tasks.Task<CalixtaSoapWebService.EventosEnvioEmailResponse> EventosEnvioEmailAsync(CalixtaSoapWebService.EventosEnvioEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> EnviaEmailAsync(
                    int cte, 
                    string email, 
                    string password, 
                    string nombreCamp, 
                    string to, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string subject, 
                    int incrustarImagen, 
                    string textEmail, 
                    string htmlEmail, 
                    int seleccionaAdjuntos, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] fileBase64, 
                    string fileNameBase64, 
                    string nombreArchivoPersonalizado, 
                    int envioSinArchivo, 
                    string fechaInicio, 
                    int horaInicio, 
                    int minutoInicio, 
                    string listasNegras, 
                    string referencia, 
                    string campoAuxiliar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajesCSV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajesCSVAsync(CalixtaSoapWebService.TransaccionCSV mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajeAsync(int idCliente, string email, string password, string tipo, string fechaHora, string telefono, string mensaje, int idivr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoEnvio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<CalixtaSoapWebService.RespEnvio> EstadoEnvioAsync(CalixtaSoapWebService.TransaccionEnvios idEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<CalixtaSoapWebService.EdoMensajes[]> EstadoMensajesAsync(CalixtaSoapWebService.TransaccionEnvios idEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajeOL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajeOLAsync(int idCliente, string email, string password, string tipo, string telefono, string mensaje, int idivr, string fechaInicio, string campoAux, string asunto, string url, string idApp, string token, CalixtaSoapWebService.Parametro[] parametros);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajeOLRef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        System.Threading.Tasks.Task<CalixtaSoapWebService.EnviaMensajeOLRefResponse> EnviaMensajeOLRefAsync(CalixtaSoapWebService.EnviaMensajeOLRefRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajeOLRef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EstadoMensajeOLRefAsync(string referencia);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajeOLRefAux", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        System.Threading.Tasks.Task<CalixtaSoapWebService.EstadoMensajeOLAuxResponse> EstadoMensajeOLAuxAsync(CalixtaSoapWebService.EstadoMensajeOLAuxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#AgregaALista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> AgregaAListaAsync(int idCliente, string email, string password, int idLista, string telefono, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ExisteEnLista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> ExisteEnListaAsync(int idCliente, string email, string password, int idLista, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EliminaDeLista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EliminaDeListaAsync(int idCliente, string email, string password, int idLista, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ConsultaSaldo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<CalixtaSoapWebService.Saldos[]> ConsultaSaldoAsync(int idCliente, string email, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Transaccion
    {
        
        private int idClienteField;
        
        private string emailField;
        
        private string passwordField;
        
        private string tipoField;
        
        private string fechaHoraField;
        
        private Mensaje[] mensajesField;
        
        private int idivrField;
        
        /// <remarks/>
        public int idCliente
        {
            get
            {
                return this.idClienteField;
            }
            set
            {
                this.idClienteField = value;
            }
        }
        
        /// <remarks/>
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string fechaHora
        {
            get
            {
                return this.fechaHoraField;
            }
            set
            {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        public Mensaje[] mensajes
        {
            get
            {
                return this.mensajesField;
            }
            set
            {
                this.mensajesField = value;
            }
        }
        
        /// <remarks/>
        public int idivr
        {
            get
            {
                return this.idivrField;
            }
            set
            {
                this.idivrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Mensaje
    {
        
        private string telefonoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Saldos
    {
        
        private int idField;
        
        private string servicioField;
        
        private double disponibleField;
        
        /// <remarks/>
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string servicio
        {
            get
            {
                return this.servicioField;
            }
            set
            {
                this.servicioField = value;
            }
        }
        
        /// <remarks/>
        public double disponible
        {
            get
            {
                return this.disponibleField;
            }
            set
            {
                this.disponibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Parametro
    {
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class EdoMensajes
    {
        
        private string tipoField;
        
        private string telefonoField;
        
        private double costoField;
        
        private string fechaHoraField;
        
        private string estadoField;
        
        private string listaField;
        
        private int idEnvioField;
        
        private int idEstadoField;
        
        private string mensajeField;
        
        private string destinoField;
        
        private string campoAuxField;
        
        /// <remarks/>
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public double costo
        {
            get
            {
                return this.costoField;
            }
            set
            {
                this.costoField = value;
            }
        }
        
        /// <remarks/>
        public string fechaHora
        {
            get
            {
                return this.fechaHoraField;
            }
            set
            {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string lista
        {
            get
            {
                return this.listaField;
            }
            set
            {
                this.listaField = value;
            }
        }
        
        /// <remarks/>
        public int idEnvio
        {
            get
            {
                return this.idEnvioField;
            }
            set
            {
                this.idEnvioField = value;
            }
        }
        
        /// <remarks/>
        public int idEstado
        {
            get
            {
                return this.idEstadoField;
            }
            set
            {
                this.idEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string destino
        {
            get
            {
                return this.destinoField;
            }
            set
            {
                this.destinoField = value;
            }
        }
        
        /// <remarks/>
        public string campoAux
        {
            get
            {
                return this.campoAuxField;
            }
            set
            {
                this.campoAuxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class RespEnvio
    {
        
        private int idField;
        
        private double fInicioField;
        
        private string camposField;
        
        private string descripcionField;
        
        private string listaField;
        
        private double porField;
        
        private int tipoField;
        
        private int idUsuarioField;
        
        private int especieField;
        
        private int estadoField;
        
        private double costoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public double fInicio
        {
            get
            {
                return this.fInicioField;
            }
            set
            {
                this.fInicioField = value;
            }
        }
        
        /// <remarks/>
        public string campos
        {
            get
            {
                return this.camposField;
            }
            set
            {
                this.camposField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string lista
        {
            get
            {
                return this.listaField;
            }
            set
            {
                this.listaField = value;
            }
        }
        
        /// <remarks/>
        public double por
        {
            get
            {
                return this.porField;
            }
            set
            {
                this.porField = value;
            }
        }
        
        /// <remarks/>
        public int tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int especie
        {
            get
            {
                return this.especieField;
            }
            set
            {
                this.especieField = value;
            }
        }
        
        /// <remarks/>
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public double costo
        {
            get
            {
                return this.costoField;
            }
            set
            {
                this.costoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class TransaccionEnvios
    {
        
        private int idClienteField;
        
        private string emailField;
        
        private string passwordField;
        
        private int idEnvioField;
        
        /// <remarks/>
        public int idCliente
        {
            get
            {
                return this.idClienteField;
            }
            set
            {
                this.idClienteField = value;
            }
        }
        
        /// <remarks/>
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int idEnvio
        {
            get
            {
                return this.idEnvioField;
            }
            set
            {
                this.idEnvioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class TransaccionCSV
    {
        
        private int idClienteField;
        
        private string emailField;
        
        private string passwordField;
        
        private string tipoField;
        
        private string fechaHoraField;
        
        private string csvField;
        
        private string mensajeField;
        
        private int idivrField;
        
        /// <remarks/>
        public int idCliente
        {
            get
            {
                return this.idClienteField;
            }
            set
            {
                this.idClienteField = value;
            }
        }
        
        /// <remarks/>
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string fechaHora
        {
            get
            {
                return this.fechaHoraField;
            }
            set
            {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        public string csv
        {
            get
            {
                return this.csvField;
            }
            set
            {
                this.csvField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public int idivr
        {
            get
            {
                return this.idivrField;
            }
            set
            {
                this.idivrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Eventos
    {
        
        private string fechaField;
        
        private string tipoField;
        
        /// <remarks/>
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EventosEnvioEmail", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EventosEnvioEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string id;
        
        public EventosEnvioEmailRequest()
        {
        }
        
        public EventosEnvioEmailRequest(int cte, string email, string password, string id)
        {
            this.cte = cte;
            this.email = email;
            this.password = password;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EventosEnvioEmailResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EventosEnvioEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public CalixtaSoapWebService.Eventos[] eventos;
        
        public EventosEnvioEmailResponse()
        {
        }
        
        public EventosEnvioEmailResponse(int code, CalixtaSoapWebService.Eventos[] eventos)
        {
            this.code = code;
            this.eventos = eventos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnviaMensajeOLRef", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EnviaMensajeOLRefRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int idivr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string campoAux;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string asunto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string idApp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public CalixtaSoapWebService.Parametro[] parametros;
        
        public EnviaMensajeOLRefRequest()
        {
        }
        
        public EnviaMensajeOLRefRequest(int idCliente, string email, string password, string tipo, string telefono, string mensaje, int idivr, string fechaInicio, string campoAux, string asunto, string url, string idApp, string token, CalixtaSoapWebService.Parametro[] parametros)
        {
            this.idCliente = idCliente;
            this.email = email;
            this.password = password;
            this.tipo = tipo;
            this.telefono = telefono;
            this.mensaje = mensaje;
            this.idivr = idivr;
            this.fechaInicio = fechaInicio;
            this.campoAux = campoAux;
            this.asunto = asunto;
            this.url = url;
            this.idApp = idApp;
            this.token = token;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnviaMensajeOLRefResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EnviaMensajeOLRefResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string referencia;
        
        public EnviaMensajeOLRefResponse()
        {
        }
        
        public EnviaMensajeOLRefResponse(int resultado, string referencia)
        {
            this.resultado = resultado;
            this.referencia = referencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstadoMensajeOLAux", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EstadoMensajeOLAuxRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string campoAux;
        
        public EstadoMensajeOLAuxRequest()
        {
        }
        
        public EstadoMensajeOLAuxRequest(int idCliente, string email, string password, string campoAux)
        {
            this.idCliente = idCliente;
            this.email = email;
            this.password = password;
            this.campoAux = campoAux;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstadoMensajeOLAuxResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EstadoMensajeOLAuxResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string id;
        
        public EstadoMensajeOLAuxResponse()
        {
        }
        
        public EstadoMensajeOLAuxResponse(int resultado, string referencia, string id)
        {
            this.resultado = resultado;
            this.referencia = referencia;
            this.id = id;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface GatewayPortTypeChannel : CalixtaSoapWebService.GatewayPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class GatewayPortTypeClient : System.ServiceModel.ClientBase<CalixtaSoapWebService.GatewayPortType>, CalixtaSoapWebService.GatewayPortType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GatewayPortTypeClient() : 
                base(GatewayPortTypeClient.GetDefaultBinding(), GatewayPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GatewayPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GatewayPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(GatewayPortTypeClient.GetBindingForEndpoint(endpointConfiguration), GatewayPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GatewayPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GatewayPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GatewayPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GatewayPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GatewayPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajesAsync(CalixtaSoapWebService.Transaccion mensajes)
        {
            return base.Channel.EnviaMensajesAsync(mensajes);
        }
        
        public System.Threading.Tasks.Task<int> EstadoEnvioEmailAsync(int cte, string email, string password, int id)
        {
            return base.Channel.EstadoEnvioEmailAsync(cte, email, password, id);
        }
        
        public System.Threading.Tasks.Task<CalixtaSoapWebService.EventosEnvioEmailResponse> EventosEnvioEmailAsync(CalixtaSoapWebService.EventosEnvioEmailRequest request)
        {
            return base.Channel.EventosEnvioEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> EnviaEmailAsync(
                    int cte, 
                    string email, 
                    string password, 
                    string nombreCamp, 
                    string to, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string subject, 
                    int incrustarImagen, 
                    string textEmail, 
                    string htmlEmail, 
                    int seleccionaAdjuntos, 
                    byte[] fileBase64, 
                    string fileNameBase64, 
                    string nombreArchivoPersonalizado, 
                    int envioSinArchivo, 
                    string fechaInicio, 
                    int horaInicio, 
                    int minutoInicio, 
                    string listasNegras, 
                    string referencia, 
                    string campoAuxiliar)
        {
            return base.Channel.EnviaEmailAsync(cte, email, password, nombreCamp, to, from, fromName, replyTo, subject, incrustarImagen, textEmail, htmlEmail, seleccionaAdjuntos, fileBase64, fileNameBase64, nombreArchivoPersonalizado, envioSinArchivo, fechaInicio, horaInicio, minutoInicio, listasNegras, referencia, campoAuxiliar);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajesCSVAsync(CalixtaSoapWebService.TransaccionCSV mensajes)
        {
            return base.Channel.EnviaMensajesCSVAsync(mensajes);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajeAsync(int idCliente, string email, string password, string tipo, string fechaHora, string telefono, string mensaje, int idivr)
        {
            return base.Channel.EnviaMensajeAsync(idCliente, email, password, tipo, fechaHora, telefono, mensaje, idivr);
        }
        
        public System.Threading.Tasks.Task<CalixtaSoapWebService.RespEnvio> EstadoEnvioAsync(CalixtaSoapWebService.TransaccionEnvios idEnvio)
        {
            return base.Channel.EstadoEnvioAsync(idEnvio);
        }
        
        public System.Threading.Tasks.Task<CalixtaSoapWebService.EdoMensajes[]> EstadoMensajesAsync(CalixtaSoapWebService.TransaccionEnvios idEnvio)
        {
            return base.Channel.EstadoMensajesAsync(idEnvio);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajeOLAsync(int idCliente, string email, string password, string tipo, string telefono, string mensaje, int idivr, string fechaInicio, string campoAux, string asunto, string url, string idApp, string token, CalixtaSoapWebService.Parametro[] parametros)
        {
            return base.Channel.EnviaMensajeOLAsync(idCliente, email, password, tipo, telefono, mensaje, idivr, fechaInicio, campoAux, asunto, url, idApp, token, parametros);
        }
        
        public System.Threading.Tasks.Task<CalixtaSoapWebService.EnviaMensajeOLRefResponse> EnviaMensajeOLRefAsync(CalixtaSoapWebService.EnviaMensajeOLRefRequest request)
        {
            return base.Channel.EnviaMensajeOLRefAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> EstadoMensajeOLRefAsync(string referencia)
        {
            return base.Channel.EstadoMensajeOLRefAsync(referencia);
        }
        
        public System.Threading.Tasks.Task<CalixtaSoapWebService.EstadoMensajeOLAuxResponse> EstadoMensajeOLAuxAsync(CalixtaSoapWebService.EstadoMensajeOLAuxRequest request)
        {
            return base.Channel.EstadoMensajeOLAuxAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> AgregaAListaAsync(int idCliente, string email, string password, int idLista, string telefono, string nombre)
        {
            return base.Channel.AgregaAListaAsync(idCliente, email, password, idLista, telefono, nombre);
        }
        
        public System.Threading.Tasks.Task<int> ExisteEnListaAsync(int idCliente, string email, string password, int idLista, string telefono)
        {
            return base.Channel.ExisteEnListaAsync(idCliente, email, password, idLista, telefono);
        }
        
        public System.Threading.Tasks.Task<int> EliminaDeListaAsync(int idCliente, string email, string password, int idLista, string telefono)
        {
            return base.Channel.EliminaDeListaAsync(idCliente, email, password, idLista, telefono);
        }
        
        public System.Threading.Tasks.Task<CalixtaSoapWebService.Saldos[]> ConsultaSaldoAsync(int idCliente, string email, string password)
        {
            return base.Channel.ConsultaSaldoAsync(idCliente, email, password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GatewayPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GatewayPort))
            {
                return new System.ServiceModel.EndpointAddress("http://www.calixtaondemand.com/ws/webServiceV8.php");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GatewayPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.GatewayPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GatewayPortTypeClient.GetEndpointAddress(EndpointConfiguration.GatewayPort);
        }
        
        public enum EndpointConfiguration
        {
            
            GatewayPort,
        }
    }
}
